version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-native-hooks-app
    env_file:
      - .env
    volumes: 
      - ".:/app"
    ports:
      - "9006:19006"
    tty: true